channels:
  - conda-forge
  - pytorch
  - nvidia
  - pyviz
dependencies:
  - pip
  - pytorch::pytorch
  - pytorch::pytorch-cuda
  - pytorch-lightning
  - pyinterp
  - xarray
  - dask
  - netCDF4
  - bottleneck
  - xrft
  - metpy
  - scipy
  - matplotlib
  - holoviews
  - pip:
      - GitPython
      - einops
      - hydra-core
      - kornia
      - tabulate
