# @package _global_

paths:
  GT: data/Obs_SPM_log10_aNam.nc
  patch: data/Obs_SPM_log10_aNam_removed_50percent_patch_again.nc

trainer:
  _target_: pytorch_lightning.Trainer
  inference_mode: False
  gradient_clip_val: 0.5
  accelerator: gpu
  devices: 1
  logger:
    _target_: pytorch_lightning.loggers.CSVLogger
    save_dir: ${hydra:runtime.output_dir}
    name: ${hydra:runtime.choices.xp}
    version: 'TestonOSE_DutchWaddenSea'
  max_epochs: 225
  callbacks:
    - _target_: src.versioning_cb.VersioningCallback
    - _target_: pytorch_lightning.callbacks.LearningRateMonitor
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      monitor: val_mse
      save_top_k: 1
      filename: '{val_mse:.4f}-{epoch:03d}'

datamodule:
  _target_: src.data_SCHISM_AugMoreRemovedPatches.BaseDataModule
  input_da: 
    _target_: src.utils.load_bbp_data
    path1: ${paths.GT}
    path2: ${paths.patch}
  domains:
    train:
      time: {_target_: builtins.slice, _args_: ['2020-01-02', '2020-09-30']}
    val:
      time: {_target_: builtins.slice, _args_: ['2020-10-01', '2020-11-26']}
    test:
      time: {_target_: builtins.slice,  _args_: ['2020-01-02', '2020-11-26']}
  xrds_kw:
    patch_dims: {time: 10, lat: 240, lon: 300}
    strides: {time: 1, lat: 240, lon: 300}
  dl_kw: {batch_size: 4, num_workers: 0}
  aug_factor: 1
  aug_only: True

model:
  _target_: src.models.Lit4dVarNet
  opt_fn:
    _target_: src.utils.cosanneal_lr_adam
    _partial_: true
    lr: 1e-3
    T_max: 175
  rec_weight:
    _target_: src.utils.get_triang_time_wei
    patch_dims: ${datamodule.xrds_kw.patch_dims}
    crop: {time: 0, lat: 0, lon: 0}
    offset: 1
  solver:
    _target_: src.models.GradSolver
    n_step: 15
    lr_grad: 0.2
    prior_cost:
      _target_: src.models.BilinAEPriorCost
      dim_in: ${datamodule.xrds_kw.patch_dims.time}
      dim_hidden: 64
      downsamp: 2
      bilin_quad: False

    obs_cost:
      _target_: src.models.BaseObsCost
    grad_mod:
      _target_: src.models.ConvLstmGradModel
      dim_in: ${datamodule.xrds_kw.patch_dims.time}
      dim_hidden: 96

entrypoints:
  - _target_: pytorch_lightning.seed_everything
    seed: 333
  - _target_: src.test.base_test
    trainer: ${trainer}
    lit_mod: ${model}
    dm: ${datamodule}
    ckpt_path: "data/checkpoints/val_mse=24.5515-epoch=197.ckpt"
