global:
  suspend: false

service:
  image:
    version: "ghcr.io/cia-oceanix/4dvarnet-turbiditymapping:1.3"
    pullPolicy: IfNotPresent
    custom:
      enabled: false

security:
  allowlist:
    enabled: false
    ip: 0.0.0.0/0
  password: changeme

environment:
  user: onyxia
  group: users

nameOverride: ""
fullnameOverride: ""


podSecurityContext:
  fsGroup: 100

securityContext: {}

userPreferences:
  darkMode: false
  language: en

init:
  standardInitPath: /opt/onyxia-init.sh
  regionInit: ''
  personalInit: ''
  personalInitArgs: ''

nodeSelector: {}
tolerations: []


networking:
  type: ClusterIP
  clusterIP: None
  service:
    port: 8888
  user:
    enabled: false


ingress:
  enabled: false
  tls: true
  annotations: []

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 500m
  #   memory: 32Gi
  # requests:
  #   cpu: 200m
  #   memory: 10Gi


startupProbe:
  failureThreshold: 60
  initialDelaySeconds: 5
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 5
